name: kittens

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kittensdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    